default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: marketplace-base_development

test:
  <<: *default
  database: marketplace-base_test

# Restart Server
# pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start